// Generates the build inputs WXT doesn't: the runtime/action icon PNGs, the OSK
// mode-icon data-URL module, the romanize-popup-window videos, and the public
// copies (manifest icons + _locales) WXT copies to the output root as-is.
//
// Manifest generation and the Firefox `background.scripts` patch — which the
// Parcel-era scripts/build-manifest.mjs + patch-firefox-manifest.mjs handled —
// are now WXT's job (see wxt.config.ts). So is the Hanja-window stylesheet,
// which Vite bundles straight from the `.scss` import (no codegen workaround).

import { Resvg } from "@resvg/resvg-js";
import { copyFileSync, cpSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = process.cwd();
const sourceImageDir = resolve(root, "resources/images");
const outputImageDir = resolve(root, "src/images");
const publicImageDir = resolve(root, "public/images");
const sourceLocalesDir = resolve(root, "src/_locales");
const publicLocalesDir = resolve(root, "public/_locales");
const sourceVideoDir = resolve(root, "resources/videos");
const outputVideoDir = resolve(root, "src/videos");
const modeIconsModulePath = resolve(root, "src/content-script/on-screen-keyboard/mode-icons.ts");

const bundledFontFamily = "NanumMyeongjo";
const bundledFontFiles = [resolve(root, "resources/fonts/Nanum_Myeongjo/NanumMyeongjo-Bold.ttf")];
const actionIconSources = {
    a: resolve(sourceImageDir, "icon_a.svg"),
    h: resolve(sourceImageDir, "icon_h.svg"),
};
const runtimeIconSource = actionIconSources.h;
const actionIconSizes = [16, 24, 32];
const runtimeIconSizes = [48, 128, 256];
// Icons the static manifest references (served from the output root as
// /images/...), so they must live in public/. The rest are bundled by Vite
// (imported with ?url in the service worker, or via CSS in the options page).
const manifestIcons = ["icon16h.png", "icon48.png", "icon128.png", "icon16a.png", "icon24a.png", "icon32a.png"];
// The getting-started page shows a browser-specific "pin the toolbar icon"
// animation. Copy the variant for the build target into the generic
// pin-{light,dark}.mp4 names the Vue component imports. Target comes from argv
// (`node scripts/gen-assets.mjs firefox`); defaults to chrome.
const target = process.argv[2] === "firefox" ? "firefox" : "chrome";
const copiedVideos = {
    chrome: { "pin-light.mp4": "chrome-lightmode-pin.mp4", "pin-dark.mp4": "chrome-darkmode-pin.mp4" },
    firefox: { "pin-light.mp4": "firefox-lightmode-pin.mp4", "pin-dark.mp4": "firefox-darkmode-pin.mp4" },
};
const modeIconDisplaySize = 16;
const modeIconRenderSizes = [16, 24, 32, 48];
const popupModeIconDisplaySize = 24;
const popupModeIconRenderSizes = [24, 36, 48, 72];

function renderIconPng(sourcePath, size) {
    const svg = readFileSync(sourcePath, "utf8");
    return new Resvg(svg, {
        fitTo: { mode: "width", value: size },
        font: {
            defaultFontFamily: bundledFontFamily,
            fontFiles: bundledFontFiles,
            loadSystemFonts: false,
            serifFamily: bundledFontFamily,
        },
    })
        .render()
        .asPng();
}

function generateIcons() {
    mkdirSync(outputImageDir, { recursive: true });
    for (const size of runtimeIconSizes) {
        writeFileSync(resolve(outputImageDir, `icon${size}.png`), renderIconPng(runtimeIconSource, size));
    }
    for (const [suffix, sourcePath] of Object.entries(actionIconSources)) {
        for (const size of actionIconSizes) {
            writeFileSync(resolve(outputImageDir, `icon${size}${suffix}.png`), renderIconPng(sourcePath, size));
        }
    }

    mkdirSync(publicImageDir, { recursive: true });
    for (const icon of manifestIcons) {
        copyFileSync(resolve(outputImageDir, icon), resolve(publicImageDir, icon));
    }
    console.log("[gen-assets] wrote icons (src/images + public/images)");
}

function generateModeIcons() {
    const dataUrl = (suffix, size) =>
        `data:image/png;base64,${renderIconPng(actionIconSources[suffix], size).toString("base64")}`;
    const srcset = (suffix, renderSizes, displaySize) =>
        renderSizes.map((size) => `${dataUrl(suffix, size)} ${size / displaySize}x`).join(", ");

    const moduleSource =
        "// GENERATED by scripts/gen-assets.mjs from resources/images/icon_{h,a}.svg.\n" +
        "// Do not edit by hand; regenerated on every build (and on `npm install`).\n" +
        `export const modeIconHangul = "${dataUrl("h", modeIconDisplaySize)}";\n` +
        `export const modeIconEnglish = "${dataUrl("a", modeIconDisplaySize)}";\n` +
        `export const modeIconHangulSrcset = "${srcset("h", modeIconRenderSizes, modeIconDisplaySize)}";\n` +
        `export const modeIconEnglishSrcset = "${srcset("a", modeIconRenderSizes, modeIconDisplaySize)}";\n` +
        `export const popupModeIconHangul = "${dataUrl("h", popupModeIconDisplaySize)}";\n` +
        `export const popupModeIconEnglish = "${dataUrl("a", popupModeIconDisplaySize)}";\n` +
        `export const popupModeIconHangulSrcset = "${srcset("h", popupModeIconRenderSizes, popupModeIconDisplaySize)}";\n` +
        `export const popupModeIconEnglishSrcset = "${srcset("a", popupModeIconRenderSizes, popupModeIconDisplaySize)}";\n`;

    writeFileSync(modeIconsModulePath, moduleSource);
    console.log("[gen-assets] wrote mode-icons.ts");
}

function copyVideos() {
    rmSync(outputVideoDir, { recursive: true, force: true });
    mkdirSync(outputVideoDir, { recursive: true });
    for (const [outName, sourceName] of Object.entries(copiedVideos[target])) {
        copyFileSync(resolve(sourceVideoDir, sourceName), resolve(outputVideoDir, outName));
    }
    console.log(`[gen-assets] copied ${target} videos (src/videos)`);
}

function copyLocalesToPublic() {
    rmSync(publicLocalesDir, { recursive: true, force: true });
    cpSync(sourceLocalesDir, publicLocalesDir, { recursive: true });
    console.log("[gen-assets] copied _locales (public/_locales)");
}

generateIcons();
generateModeIcons();
copyVideos();
copyLocalesToPublic();
